### ISSUE TITLE
Back light no longer works on Adafruit 16x2 Character LCD using version 1.5

### ISSUE THREAD

**Issue by whatwouldbradydo** [travistyoj/piforcetools#2]
Hi, It seems the back light no longer works on Adafruit 16x2 Character LCD using version 1.5, I have tried this on RPi2 and RPi3.

It flashes for a second when first booting then turns off. I noticed someone else mention it so I don't think it's my screen http://www.neo-geo.com/forums/showthread.php?250758-Piforce-Tools-Support-Thread&p=4054507&viewfull=1#post4054507

I can still see the screen is on and move through the menu's it's just the back light.

thanks

**Comment by whatwouldbradydo** [comment]
http://www.neo-geo.com/forums/showthread.php?250758-Piforce-Tools-Support-Thread&p=4092896&viewfull=1#post4092896

> For those of you that are using the old white text on Blue background LCD (16x2) and wondering why the backlight flickers on for a second and then stays off, you need to edit piforcetools.py file in the piforcetools directory and comment / remove the following line:

lcd.backlight(lcd.BLUE)

**Comment by travistyoj** [comment]
The current code base supports the RGB version of the LCD plate.  I have not found a way to autodetect whether the plate is RGB or non-RGB
